name: flappwrite_ui
description: A new Flutter package project.
version: 0.0.1
homepage: https://dlohani.com.np

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  appwrite: ^8.1.0
  appwrite_auth_kit: ^0.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
